"""Evidence-first retrieval-augmented generation boundaries."""

from medaudit.rag.aggregation import group_decomposition_evidence
from medaudit.rag.application import (
    GroundedSynthesisApplication,
    RoutedSynthesisResult,
)
from medaudit.rag.context import (
    CompiledContext,
    CompiledContextGroup,
    ContextExclusion,
    ContextExclusionReason,
    ContextItem,
    ContextItemKind,
    ContextStatus,
    ContextTrust,
    TokenEstimator,
    Utf8ByteTokenEstimator,
    compile_decomposed_context,
    context_integrity_is_valid,
)
from medaudit.rag.decomposition import DeterministicDecompositionExecutor
from medaudit.rag.evidence_safety import (
    EvidenceSafetyAssessment,
    EvidenceSafetyFinding,
    EvidenceSafetySignal,
    assess_decomposed_evidence,
    inspect_evidence_text,
)
from medaudit.rag.integration import (
    CompiledContextGateway,
    CompiledRequestMode,
    CompiledRequestResult,
    CompiledRequestStatus,
    CompiledRequestTelemetry,
)
from medaudit.rag.models import (
    DecompositionEvidenceBundle,
    DecompositionExecution,
    DecompositionExecutionStatus,
    Evidence,
    EvidenceLocation,
    ExecutedQueryStep,
    RetrievalDecision,
    RetrievalStatus,
    RoutedRetrievalDecision,
    StepEvidenceGroup,
)
from medaudit.rag.orchestration import (
    GroundedSynthesisOrchestrator,
    SynthesisMode,
    SynthesisResult,
    SynthesisStatus,
    SynthesisTelemetry,
)
from medaudit.rag.pipeline import (
    EvidenceFirstPipeline,
    FrozenTopScorePolicy,
    RoutedCompiledRequestResult,
    RoutedEvidenceFirstPipeline,
)
from medaudit.rag.prompt import (
    DECOMPOSED_GROUNDED_INSTRUCTION,
    build_compiled_decomposed_grounded_request,
    build_decomposed_grounded_request,
    build_grounded_request,
)
from medaudit.rag.validation import (
    ClaimSupport,
    DecomposedGroundedAnswer,
    GroundedAnswer,
    GroundedClaim,
    validate_decomposed_grounded_response,
    validate_grounded_response,
)

__all__ = [
    "DECOMPOSED_GROUNDED_INSTRUCTION",
    "ClaimSupport",
    "CompiledContext",
    "CompiledContextGateway",
    "CompiledContextGroup",
    "CompiledRequestMode",
    "CompiledRequestResult",
    "CompiledRequestStatus",
    "CompiledRequestTelemetry",
    "ContextExclusion",
    "ContextExclusionReason",
    "ContextItem",
    "ContextItemKind",
    "ContextStatus",
    "ContextTrust",
    "DecomposedGroundedAnswer",
    "DecompositionEvidenceBundle",
    "DecompositionExecution",
    "DecompositionExecutionStatus",
    "DeterministicDecompositionExecutor",
    "Evidence",
    "EvidenceFirstPipeline",
    "EvidenceLocation",
    "EvidenceSafetyAssessment",
    "EvidenceSafetyFinding",
    "EvidenceSafetySignal",
    "ExecutedQueryStep",
    "FrozenTopScorePolicy",
    "GroundedAnswer",
    "GroundedClaim",
    "GroundedSynthesisApplication",
    "GroundedSynthesisOrchestrator",
    "RetrievalDecision",
    "RetrievalStatus",
    "RoutedCompiledRequestResult",
    "RoutedEvidenceFirstPipeline",
    "RoutedRetrievalDecision",
    "RoutedSynthesisResult",
    "StepEvidenceGroup",
    "SynthesisMode",
    "SynthesisResult",
    "SynthesisStatus",
    "SynthesisTelemetry",
    "TokenEstimator",
    "Utf8ByteTokenEstimator",
    "assess_decomposed_evidence",
    "build_compiled_decomposed_grounded_request",
    "build_decomposed_grounded_request",
    "build_grounded_request",
    "compile_decomposed_context",
    "context_integrity_is_valid",
    "group_decomposition_evidence",
    "inspect_evidence_text",
    "validate_decomposed_grounded_response",
    "validate_grounded_response",
]
